### ISSUE TITLE
cvxopt 1.1.9 missing umfpack.h

### ISSUE THREAD

**Issue by nonhermitian** [cvxopt/cvxopt#78]
We use cvxopt to do some quantum information processing routines in Python.  The latest version (1.1.9), installed via pip fails to install due to missing `umfpack.h`:

```
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/home/travis/miniconda/envs/test-environment/include/python3.5m -c src/C/umfpack.c -o build/temp.linux-x86_64-3.5/src/C/umfpack.o
    src/C/umfpack.c:23:21: fatal error: umfpack.h: No such file or directory
     #include "umfpack.h"
```

Of course, since the umfpack interface is new in 1.1.9, reverting to 1.1.8 fixes the issue.

**Comment by martinandersen** [comment]
Please see the updated [installation instructions](http://cvxopt.org/install/index.html): we have removed the SuiteSparse source code from CVXOPT since SuiteSparse is available as a package in Ubuntu 16.04 and macOS (via homebrew). You can also build the relevant components of SuiteSparse when building CVXOPT, but this requires that you download the SuiteSparse source separately and set `CVXOPT_SUITESPARSE_SRC_DIR` to the SuiteSparse source directory.

**Comment by nonhermitian** [comment]
Yes, I now see the relevant section.  Thank you for the quick reply.

**Comment by martinandersen** [comment]
It should be sufficient to add this:

```
wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz
tar -xf SuiteSparse-4.5.3.tar.gz
export CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse
```

**Comment by nonhermitian** [comment]
I don't think we loose much by testing against 1.1.8, so it is easy to just pip install that version and not have to install all of suitesparse for a few unittests.

**Comment by martinandersen** [comment]
You probably don't loose much, but in both cases you end up building the same parts of SuiteSparse.

**Comment by arranger1044** [comment]
Installing from pip seems broken, can you check for the installed requirements of SuiteSparse as well?

**Comment by martinandersen** [comment]
I am not sure what you are asking. You need either a shared SuiteSparse library or the SuiteSparse source to install CVXOPT using `pip`. The default location of shared libraries depends on your OS, so you may need to manually specify the path to SuiteSparse via the `CVXOPT_SUITESPARSE_XXX_DIR` environment variables (see [installation instructions](http://cvxopt.org/install/index.html)). Alternatively, you can use `conda` to install CVXOPT and it's dependencies from [conda-forge](https://github.com/conda-forge/cvxopt-feedstock).

**Comment by gdamirna** [comment]
I have the similar problem and don't know how to fix. I am following this instruction for windows installantion [http://cvxopt.org/install/index.html]

When I try to execute this command:
python setup.py build --compiler=mingw32

I get this:

running build
running build_py
UPDATING build\lib.win-amd64-2.7\cvxopt/_version.py
set build\lib.win-amd64-2.7\cvxopt/_version.py to '1.1.9+1.gd8bd930'
running build_ext
building 'umfpack' extension
C:\Python27\Scripts\gcc.exe -mdll -O -Wall -I/usr/include/suitesparse -IC:\Python27\include -IC:\Python27\PC -c src/C/umfpack.c -o build\temp.win-amd64-2.7\Release\src\c\umfpack.o
src/C/umfpack.c:23:21: **fatal error: umfpack.h: No such file or directory
 #include "umfpack.h"**
                     ^
compilation terminated.
error: command 'C:\\Python27\\Scripts\\gcc.exe' failed with exit status 1

Please, how can I solve this?

**Comment by wkschwartz** [comment]
In case anyone gets here Googling `"umfpack.h"` as I did, here's how I made installation work on Raspbian 10 (buster) armv71:

```console
$ sudo apt install libsuitesparse-dev  # per installation instructions cited above
$ export CPPFLAGS="-I/usr/include/suitesparse"  # <-- NEW STEP
$ pip install cvxopt
```

**Comment by harrowm2** [comment]
To get this to work on a Mac with Homebrew and Python 3.9.2, I had to issue this command before installing cvxopt:

brew install suite-sparse
pip3 install cvxopt

**Comment by iammujtaba** [comment]
> To get this to work on a Mac with Homebrew and Python 3.9.2, I had to issue this command before installing cvxopt:
> 
> brew install suite-sparse pip3 install cvxopt

It's not working with Python 3.9.7 and Mac M1 and Os- Montrey

**Comment by lionettis** [comment]
```
CVXOPT_SUITESPARSE_LIB_DIR=/opt/homebrew/Cellar/suite-sparse/VERSION/lib/ CVXOPT_SUITESPARSE_INC_DIR=/opt/homebrew/Cellar/suite-sparse/VERSION/include/ pip install cvxopt
```
seems to do the trick for me

**Comment by BoHuang2018** [comment]
> ```
> CVXOPT_SUITESPARSE_LIB_DIR=/opt/homebrew/Cellar/suite-sparse/VERSION/lib/ CVXOPT_SUITESPARSE_INC_DIR=/opt/homebrew/Cellar/suite-sparse/VERSION/include/ pip install cvxopt
> ```
> 
> seems to do the trick for me after `brew install suite-sparse`.

This does not work on my MacbookPro (2021, M1), still stuck by the `umfpack.h file not found` error 

```
src/C/umfpack.c:23:10: fatal error: 'umfpack.h' file not found
      #include "umfpack.h"
               ^~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```

**Comment by asross** [comment]
I had to go a bit further than the other Homebrew + Mac answers and basically specify everything:
```
CVXOPT_SUITESPARSE_LIB_DIR=/opt/homebrew/Cellar/suite-sparse/5.13.0/lib/ \
CVXOPT_SUITESPARSE_INC_DIR=/opt/homebrew/Cellar/suite-sparse/5.13.0/include/ \
CVXOPT_GSL_LIB_DIR=/opt/homebrew/Cellar/gsl/2.7.1/lib/ \
CVXOPT_GSL_INC_DIR=/opt/homebrew/Cellar/gsl/2.7.1/include/ \
CVXOPT_FFTW_LIB_DIR=/opt/homebrew/Cellar/fftw/3.3.10_1/lib/ \
CVXOPT_FFTW_INC_DIR=/opt/homebrew/Cellar/fftw/3.3.10_1/include/ \
CVXOPT_GLPK_LIB_DIR=/opt/homebrew/Cellar/glpk/5.0/lib/ \
CVXOPT_GLPK_INC_DIR=/opt/homebrew/Cellar/glpk/5.0/include/ \
pip install cvxopt
```
This did work though!

**Comment by FaridAlavi** [comment]
I am wondering why this ticket is closed. The installation from pip is broken.

**Comment by ddfont** [comment]
Slightly different worked for me

```
CVXOPT_SUITESPARSE_LIB_DIR=/opt/homebrew/Cellar/suite-sparse/7.8.3/lib/ CVXOPT_SUITESPARSE_INC_DIR=/opt/homebrew/Cellar/suite-sparse/7.8.3/include/suitesparse/ pip install cvxopt==1.3.2
```
